FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential default-jdk git graphviz less libtool-bin \
  python3 python3-rdflib wget
