FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && apt-get -y install --no-install-recommends \
  build-essential git graphviz less libtool-bin \
  python3 python3-psutil python3-rdflib python3-requests python3-simplejson \
  wget
